import { useEffect, useState } from 'react'
import { Check, ClipboardCheck, RefreshCcw, TriangleAlert, X } from 'lucide-react'
import { api, mediaUrl } from '../api/client'
import type { Species } from '../types'
import { cleanChineseDisplayName, localTaxonName } from '../utils/taxonNames'

interface ReviewItem {
  id:number; job_id:number; track_id:number; species_id:number|null; label:string; scientific_name:string;
  category:string; confidence:number; timestamp_ms:number; bbox:Record<string,number>; review_status:string; review_note:string
}

export default function ReviewPage(){
  const[items,setItems]=useState<ReviewItem[]>([]);const[species,setSpecies]=useState<Species[]>([]);const[selected,setSelected]=useState<ReviewItem|null>(null);const[speciesId,setSpeciesId]=useState('');const[note,setNote]=useState('');const[frameUrl,setFrameUrl]=useState('');const[frameError,setFrameError]=useState('')
  const load=()=>Promise.all([api<ReviewItem[]>('/api/review/queue'),api<Species[]>('/api/species')]).then(([queue,all])=>{setItems(queue);setSpecies(all);setSelected(current=>current&&queue.some(i=>i.id===current.id)?current:queue[0]??null)})
  useEffect(()=>{void load()},[])
  useEffect(()=>{setSpeciesId(selected?.species_id?String(selected.species_id):'');setNote(selected?.review_note||'');setFrameUrl('');setFrameError('');if(selected){api<{url:string}>(`/api/videos/jobs/${selected.job_id}/frame?timestamp_ms=${selected.timestamp_ms}`).then(r=>setFrameUrl(mediaUrl(r.url))).catch(e=>setFrameError(e instanceof Error?e.message:'关键帧加载失败'))}},[selected])
  const submit=async(status:'confirmed'|'dismissed'|'needs_training')=>{if(!selected)return;const chosen=species.find(s=>String(s.id)===speciesId);await api(`/api/review/detections/${selected.id}`,{method:'PATCH',body:JSON.stringify({species_id:chosen?.id??null,label:chosen?.common_name||selected.label,scientific_name:chosen?.scientific_name||selected.scientific_name,category:chosen?.category||selected.category,status,note})});setSelected(null);await load()}
  return <div className="page-stack"><div className="page-intro"><div><span className="eyebrow">HUMAN-IN-THE-LOOP</span><h2>人工复核工作台</h2><p>优先呈现需复核、未匹配物种与模型冲突；修正结果进入下一版训练清单。</p></div><button className="ghost-btn" onClick={()=>void load()}><RefreshCcw/>刷新队列</button></div>
  <div className="review-layout"><section className="panel review-canvas">{selected?<><div className="review-preview">{frameUrl?<img src={frameUrl} alt={`任务 ${selected.job_id} 关键帧`}/>:<div className="review-placeholder">正在提取任务 #{selected.job_id} · {(selected.timestamp_ms/1000).toFixed(1)}s 关键帧<br/><small>{frameError||'请稍候…'}</small></div>}<div className="review-box" style={{left:`${selected.bbox.x*100}%`,top:`${selected.bbox.y*100}%`,width:`${selected.bbox.width*100}%`,height:`${selected.bbox.height*100}%`}}><span>{selected.label} · {Math.round(selected.confidence*100)}%</span></div></div><div className="review-form"><label>修正物种<select value={speciesId} onChange={e=>setSpeciesId(e.target.value)}><option value="">无具体物种 / 排除</option>{species.map(s=><option key={s.id} value={s.id}>{cleanChineseDisplayName(localTaxonName({ label: s.common_name, scientificName: s.scientific_name, category: s.category }), s.common_name)}</option>)}</select></label><label>复核备注<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="说明判断依据、遮挡、光照或需补充的数据"/></label></div><div className="review-toolbar"><button className="primary-btn" onClick={()=>void submit('confirmed')}><Check/>确认标注</button><button className="ghost-btn" onClick={()=>void submit('needs_training')}><TriangleAlert/>加入训练集</button><button className="ghost-btn" onClick={()=>void submit('dismissed')}><X/>排除误报</button></div></>:<div className="empty-state">复核队列已经清空</div>}</section><aside className="panel"><div className="panel-head"><div><span className="eyebrow">REVIEW QUEUE</span><h3>待复核项目</h3></div><ClipboardCheck/></div>{items.map(item=><button className={`review-item ${selected?.id===item.id?'selected':''}`} key={item.id} onClick={()=>setSelected(item)}><TriangleAlert/><div><strong>{item.label||'未知目标'} · {Math.round(item.confidence*100)}%</strong><span>任务 #{item.job_id} · Track #{item.track_id}</span></div></button>)}</aside></div></div>
}
