import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CloudSun, Filter, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import SpeciesAvatar from '../components/SpeciesAvatar'
import SpeciesModal from '../components/SpeciesModal'
import type { Species } from '../types'
const categories=[['','全部'],['mammal','哺乳动物'],['bird','鸟类'],['plant','植物'],['insect','昆虫'],['reptile','爬行动物'],['amphibian','两栖动物']]
export default function SpeciesPage(){const[items,setItems]=useState<Species[]>([]);const[q,setQ]=useState('');const[cat,setCat]=useState('');const[selected,setSelected]=useState<number|null>(null);useEffect(()=>{api<Species[]>('/api/species').then(setItems)},[]);const filtered=useMemo(()=>items.filter(i=>(!cat||i.category===cat)&&(!q||`${i.common_name}${i.scientific_name}${i.english_name}`.toLowerCase().includes(q.toLowerCase()))),[items,q,cat]);return <div className="page-stack"><div className="page-intro"><div><span className="eyebrow">NATURE ATLAS</span><h2>自然图鉴</h2><p>物种百科、我的收藏和现象与行为统一放在这里；观察记录仍在“观察记录”页单独管理。</p></div><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索中文名、学名或英文名"/></div></div><div className="mode-switch"><Link className="active" to="/species"><BookOpen/>物种百科</Link><Link to="/collection"><Sparkles/>我的收藏</Link><Link to="/classroom"><CloudSun/>现象与行为</Link></div><div className="filter-row"><Filter size={17}/>{categories.map(([value,label])=><button className={cat===value?'active':''} key={value} onClick={()=>setCat(value)}>{label}</button>)}</div><div className="species-grid">{filtered.map(s=><button className="species-card" key={s.id} onClick={()=>setSelected(s.id)}><div className="species-card-top"><SpeciesAvatar species={s}/><span className="rarity-stars">{'★'.repeat(s.rarity)}{'☆'.repeat(5-s.rarity)}</span></div><h3>{s.common_name}</h3><em>{s.scientific_name}</em><p>{s.traits}</p><div className="species-card-foot"><span style={{color:s.color}}>{s.category}</span><span><ShieldCheck size={14}/>{s.protection_level}</span></div></button>)}</div>{selected&&<SpeciesModal speciesId={selected} onClose={()=>setSelected(null)}/>}</div>}
