import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CloudSun, Filter, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import SpeciesAvatar from '../components/SpeciesAvatar'
import SpeciesModal from '../components/SpeciesModal'
import type { Species } from '../types'
const categories=[['','全部'],['mammal','哺乳动物'],['bird','鸟类'],['plant','植物'],['insect','昆虫'],['reptile','爬行动物'],['amphibian','两栖动物']]
const categoryName=(value:string)=>categories.find(([key])=>key===value)?.[1]||value||'未分类'
const cleanBrief=(s:Species)=>{const text=(s.traits||s.ecology_value||s.habitat||'').trim();return /本地 BioCLIP|400721|资料生成中|待 AI|原型检索|具体分类单元/.test(text)?'':text}
export default function SpeciesPage(){const[items,setItems]=useState<Species[]>([]);const[q,setQ]=useState('');const[cat,setCat]=useState('');const[selected,setSelected]=useState<number|null>(null);useEffect(()=>{api<Species[]>('/api/species?mine=true').then(setItems)},[]);const filtered=useMemo(()=>items.filter(i=>(!cat||i.category===cat)&&(!q||`${i.common_name}${i.scientific_name}${i.english_name}`.toLowerCase().includes(q.toLowerCase()))),[items,q,cat]);return <div className="page-stack"><div className="page-intro"><div><span className="eyebrow">NATURE ATLAS</span><h2>自然图鉴</h2><p>识别过、认识过、观察过和问过的动植物都会收进这里；观察事件仍在“观察记录”里单独保存。</p></div><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索中文名、学名或英文名"/></div></div><div className="mode-switch"><Link className="active" to="/species"><BookOpen/>物种科普</Link><Link to="/collection"><Sparkles/>物种收藏</Link><Link to="/classroom"><CloudSun/>自然现象与动物行为</Link></div><div className="filter-row"><Filter size={17}/>{categories.map(([value,label])=><button className={cat===value?'active':''} key={value} onClick={()=>setCat(value)}>{label}</button>)}</div><div className="species-grid">{filtered.map(s=>{const brief=cleanBrief(s);return <button className="species-card" key={s.id} onClick={()=>setSelected(s.id)}><div className="species-card-top"><SpeciesAvatar species={s}/><span className="rarity-stars">{'★'.repeat(s.rarity)}{'☆'.repeat(5-s.rarity)}</span></div><h3>{s.common_name}</h3><em>{s.scientific_name}</em>{brief&&<p>{brief}</p>}<div className="species-card-foot"><span style={{color:s.color}}>{categoryName(s.category)}</span><span><ShieldCheck size={14}/>{s.protection_level}</span></div></button>})}</div>{!filtered.length&&<section className="panel empty-state">还没有加入自然图鉴的物种。拍照识别、视频识别或在自然问答中询问具体物种后会自动加入。</section>}{selected&&<SpeciesModal speciesId={selected} onClose={()=>setSelected(null)}/>}</div>}
